CREATE TABLE specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(160) NOT NULL,

    slug VARCHAR(180) NOT NULL UNIQUE,

    summary VARCHAR(500) NOT NULL,

    image VARCHAR(300),

    display_order INTEGER NOT NULL DEFAULT 0,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT chk_specialties_display_order
        CHECK (display_order >= 0)
);


CREATE TABLE specialty_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    specialty_id BIGINT NOT NULL,

    title VARCHAR(180),

    content TEXT NOT NULL,

    display_order INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_specialty_sections_specialty
        FOREIGN KEY (specialty_id)
        REFERENCES specialties(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_specialty_sections_display_order
        CHECK (display_order >= 0)
);


CREATE INDEX idx_specialties_active_order
    ON specialties(active, display_order);


CREATE INDEX idx_specialty_sections_specialty_order
    ON specialty_sections(specialty_id, display_order);